name: islami_app
description: "Islamic app providing prayer times, Quran recitation, and daily adhkar."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.8.1
dependencies:
  alarm: ^5.1.5
  audio_service: ^0.18.18
  audio_session: ^0.1.24
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  device_info_plus: ^11.2.0
  geolocator: ^13.0.2
  get_it: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  introduction_screen: ^4.0.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.42
  lottie: ^3.3.2
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.6.0
  retrofit_generator: ^9.7.0
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  timezone: ^0.9.4

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/gifs/
    - assets/alazan/
    - assets/saly_3la_muhammed/
  fonts:
    - family: Janna-LT
      fonts:
        - asset: assets/fonts/ArbFONTS-Janna-LT-Regular.ttf
    - family: kamali
      fonts:
        - asset: assets/fonts/kamali.regular.ttf
    - family: amiri
      fonts:
        - asset: assets/fonts/amiri_regular.ttf
flutter_assets:
  assets_path: assets/
  output_path: lib/core/helpers/
  filename: app_assets.dart
  field_prefix: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/last_logo_islami.png"
  adaptive_icon_foreground: "assets/images/last_logo_islami.png"
  adaptive_icon_background: "#202020"
  min_sdk_android: 21
